from .import views
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views


app_name = "reco_gest"

urlpatterns = [
    path('modules/recttes/tableau-de-bord', views.dashboard_recette,name="dashboard_recette"),
    path('provinces', views.provinces,name="provinces"),
    path('villes', views.villes,name="villes"),
    path('type-magasin', views.type_magasin,name="type_magasin"),
    path('type-compte', views.type_compte,name="type_compte"),
    path('creer-magasin', views.creer_magasin,name="creer_magasin"),
    path('creer-compte', views.creer_compte,name="creer_compte"),
    path('compte/<int:id>/details', views.voir_details_compte,name="voir_details_compte"),
    path('liste-magasins', views.liste_magasin,name="liste_magasin"),
    path('recette-airtel-money', views.recette_airtel,name="recette_airtel"),
    path('recette-mobi-cash', views.recette_moov,name="recette_moov"),
    path('recette-moov', views.recette_moov,name="recette_moov"),
    path('recuper-province', views.get_province,name="get_province"),
    path('recuper-ville', views.get_ville,name="get_ville"),
    path('recuper-type-compte', views.get_type_compte,name="get_type_compte"),
    path('edition/<int:id>/magasin', views.editer_magasin,name="editer_magasin"),
    path('type-de-magasin/<str:nomtypemag>/par-province', views.magasin_par_province,name="magasin_par_province"),
    path('type-de-magasin/<str:nomtypemag>/<str:ville>', views.magasin_par_ville,name="magasin_par_ville"),
    path('nouvel-utilisateur', views.creer_user,name="creer_user"),
    #path('<str:lib_type_mag>/<str:nom_ville>', views.type_mag_dans_ville,name="type_mag_dans_ville"),
    path('recuper-type-magasin', views.get_typemagasin,name="get_typemagasin"),
    path('liste-des-comptes', views.liste_compte,name="liste_compte"),
    path('module/utilisateurs/liste-utilisateurs', views.liste_utilisateurs,name="liste_utilisateurs"),
    path('type-magasin-dune-ville', views.type_mag_dune_ville,name="type_mag_dune_ville"),
    path('magasin-dun-type', views.magasins_dun_type,name="magasins_dun_type"),
    path('page-magasin', views.page_magasin,name="page_magasin"),
    path('activate/<uidb64>/<token>/', views.activate,name='activate'),
    path('index2', views.index2,name="index2"),
    path('index4', views.index4,name="index4"),
    path('index5', views.index5,name="index5"),
    path('connexion', views.connexion,name="connexion"),
    path('deconnexion', views.deconnexion,name="deconnexion"),
    path('utilisateur/<int:id>/profile', views.profile,name="profile"),
    path('utilisateur/<int:id>/editer', views.editer_utilisateur,name="editer_utilisateur"),
    path('magasins/<str:libelle_typemag>', views.detail_type_mag,name="detail_type_mag"),
    path('magasin/<int:id>/details', views.detail_magasin,name="detail_magasin"),
    path('toutes-les-recettes', views.page_des_recettes,name="page_des_recettes"),
    path('evolution-achats-ckdo', views.reporting,name="reporting"),
    path('choisir-module', views.choisir_module,name="choisir_module"),
    path('module/utlisateurs/tableau-de-bord', views.dashboard_user,name="dashboard_user"),
    path('module/reporting/tableau-de-bord', views.dashboard_reporting,name="dashboard_reporting"),
    path('recettes-par-magasin', views.recette_par_magasin,name="recette_par_magasin"),
    path('module/reporting/provinces', views.reporting_provinces,name="reporting_provinces"),
    path('module/reporting/villes', views.reporting_villes,name="reporting_villes"),
    path('module/reporting/magasins', views.reporting_magasins,name="reporting_magasins"),
    path('changer-module', views.changer_module,name="changer_module"),
    path('recuperer-compte', views.recuperer_infos_compte,name="recuperer_infos_compte"),
    path('suppression-operateur', views.supprimer_operateur,name="supprimer_operateur"),
    path('desactiver-utilisateur', views.desactiver_user,name="desactiver_user"),
    path('editer-compte', views.editer_compte,name="editer_compte"),
]