# Generated by Django 4.1.5 on 2023-02-02 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteMarchand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(max_length=30)),
                ('libelle_compte', models.CharField(max_length=50)),
                ('numero_telephone', models.CharField(max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_magasin', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('point_repere', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_general', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('caissier', models.BooleanField(default=False)),
                ('visiteur', models.BooleanField(default=True)),
                ('directeur', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ville', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_reconciliations.province')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='utilisateurs/photos')),
                ('telephone', models.CharField(max_length=10)),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.magasin')),
                ('roles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.roles')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('responsable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_transaction', models.CharField(max_length=50)),
                ('nb_operation', models.IntegerField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('msisdn', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('devise', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.CharField(max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.comptemarchand')),
            ],
        ),
        migrations.AddField(
            model_name='magasin',
            name='chef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable', to='gestion_reconciliations.utilisateur'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='type_magasin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.typemagasin'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typesmagasins', to='gestion_reconciliations.ville'),
        ),
        migrations.AddField(
            model_name='comptemarchand',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.magasin'),
        ),
    ]
