# Generated by Django 4.1.5 on 2023-02-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemagasin',
            name='code_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
