# Generated by Django 4.1.5 on 2023-02-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0003_remove_typemagasin_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecompte',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
