# Generated by Django 4.1.5 on 2023-02-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0004_typecompte_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='chef',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='gestion_reconciliations.utilisateur'),
        ),
    ]
