# Generated by Django 4.1.5 on 2023-02-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0006_magasin_latitude_magasin_longitude_typemagasin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='type_magasin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins', to='gestion_reconciliations.typemagasin'),
        ),
        migrations.AlterField(
            model_name='typemagasin',
            name='libelle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
