# Generated by Django 4.1.5 on 2023-02-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0008_alter_magasin_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='gestion_reconciliations.province'),
        ),
    ]
