# Generated by Django 4.1.5 on 2023-02-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0009_alter_ville_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptemarchand',
            name='type_compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.typecompte'),
        ),
    ]
