# Generated by Django 4.1.5 on 2023-02-22 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_reconciliations', '0010_alter_comptemarchand_type_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_reconciliations.ville'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_affectation', models.DateTimeField(auto_now_add=True)),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_reconciliations.utilisateur')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_reconciliations.magasin')),
            ],
        ),
    ]
