# Generated by Django 4.1.5 on 2023-03-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0012_utilisateur_est_connecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptemarchand',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes', to='gestion_reconciliations.magasin'),
        ),
        migrations.CreateModel(
            name='InfosConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connextion', models.DateTimeField(auto_now_add=True)),
                ('date_deconnexion', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_reconciliations.utilisateur')),
            ],
        ),
    ]
