# Generated by Django 4.1.5 on 2023-03-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reconciliations', '0013_alter_comptemarchand_magasin_infosconnexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='roles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reconciliations.roles'),
        ),
    ]
